Repository ec-europa/eubfr-data-lake, pull requests merged in 2018-11, with the labels that each got.

#170 fix(etl): correct type field in BUDG ETL - EUBFR-220
  docs/types/etls/budg-xls.md
  services/ingestion/etl/budg/xls/src/lib/transform.js
  services/ingestion/etl/budg/xls/test/unit/lib/__snapshots__/transform.spec.js.snap
Labels: tag: bug fix

#172 fix(etl): correct type field for BUDG - EUBFR-220
  services/ingestion/etl/budg/xls/src/lib/transform.js
  services/ingestion/etl/budg/xls/test/stubs/record2.json
  services/ingestion/etl/budg/xls/test/unit/lib/__snapshots__/transform.spec.js.snap
  services/ingestion/etl/budg/xls/test/unit/lib/transform.spec.js
Labels: process: review needed, tag: bug fix

#174 feat(secrets-manager): improve workflows using AWS Secrets Manager service - EUBFR-224
  config.example.json
  demo/dashboard/server/serverless.yml
  demo/dashboard/server/src/api/delete.js
  demo/dashboard/server/src/api/download.js
  demo/dashboard/server/src/api/signedUrl.js
  demo/dashboard/server/src/api/update.js
  demo/dashboard/server/src/lib/request.js
  scripts/cleaning/delete-demo.js
  tools/eubfr-cli/bin/eubfr-cli-content.js
  tools/eubfr-cli/lib/getAllProducers.js
  tools/eubfr-cli/lib/getProducerCredentials.js
Labels: tag: new feature

#168 feat(etl): add data from DEVCO - EUBFR-217
  docs/types/etls/devco-csv.md
  scripts/cleaning/delete.js
  scripts/deployment/deploy-demo.sh
  scripts/deployment/deploy.sh
  scripts/documentation/docs-md.js
  services/ingestion/etl/devco/csv/.babelrc
  services/ingestion/etl/devco/csv/README.md
  services/ingestion/etl/devco/csv/package.json
  services/ingestion/etl/devco/csv/serverless.yml
  services/ingestion/etl/devco/csv/src/events/onParseCSV.js
  services/ingestion/etl/devco/csv/src/lib/sns.js
  services/ingestion/etl/devco/csv/src/lib/transform.js
  services/ingestion/etl/devco/csv/src/lib/uploadFromStream.js
  services/ingestion/etl/devco/csv/test/stubs/record.json
  services/ingestion/etl/devco/csv/test/unit/events/onParseCSV.spec.js
  services/ingestion/etl/devco/csv/test/unit/lib/__snapshots__/transform.spec.js.snap
  services/ingestion/etl/devco/csv/test/unit/lib/transform.spec.js
  services/ingestion/etl/devco/csv/webpack.config.js
Labels: process: under review, tag: new feature
